### ISSUE TITLE
Still experiencing latency issue with Threadpool and ConsumerDispatchConcurrency

### ISSUE THREAD

**Issue by adickin** [lukebakken/so-c_sharp-latency-72805093#1]
Hello Luke, 

Thanks for helping me out with this issue.  I made your latest changes to my code and I still experience the issue I'm seeing.  I also double checked that my .net version is 6.0 and my rabbitmq version is 6.4.0.  I did notice you changed the target host, I just want to ask if you updated your clumsy filter to the address of that server.  I know that if I used localhost for the host, clumsy wouldn't introduce lag as the filter in my readme only affects 127.x.x.x addresses.

Please let me know if there is anything I can collect for diagnostics to help.  

Thank you.

**Comment by lukebakken** [comment]
Yep I changed the filter to `ip.DstHost == 192.168.1.5`, the ip of my RabbitMQ server. I was going to screenshot that but it didn't work.

I'll return to this the week of July 10.

**Comment by adickin** [comment]
Thanks Luke, lets chat next week.

**Comment by adickin** [comment]
Hey Luke,

I hope your PTO went well.  I've recorded a video that shows the problem I'm seeing, hopefully this helps.  You'll see in the video that the time between messages for the receiver is 200ms but jumps to ~500ms latency when I turn on clumsy.  Once I turn clumsy off again you'll see the receiver get all the backlogged messages at once.  I can do this exact same test with they python client and I wont see an issue.  Let me know if there's anything else I can provide. 

https://user-images.githubusercontent.com/72103555/178355945-601e0cd5-3d42-4e70-8d22-42f408b1f888.mp4

**Comment by lukebakken** [comment]
Thanks, I'm hoping to find time this week to get to this.

**Comment by lukebakken** [comment]
@adickin - How are you running RabbitMQ? Docker desktop on Windows?

**Comment by lukebakken** [comment]
I believe I can see the issue using Clumsy, so I decided to see if I can reproduce it using Toxiproxy. Instructions here:

https://github.com/lukebakken/so-c_sharp-latency-72805093#using-toxiproxy-instead-of-clumsy

I do _not_ see the same issue using Toxiproxy, which could be due to a number of things, including not using it in the same manner as clumsy.

I can't explain the difference in behavior between the Pika and C# receiver. I double-checked the socket receive buffer size used by Python and its 64KiB, the same as the C# client. Since both programs are using AutoAck there is NO explanation why delay of TCP data to RabbitMQ (which basically are TCP ACKs) would only affect the C# client.

Anyway, give Toxiproxy a whirl in your environment. I can't spend more time on this as I have more pressing work to do!

**Comment by lukebakken** [comment]
PS if you do find an explanation for this behavior, I would really, really appreciate a follow-up!

**Comment by adickin** [comment]
I am using docker windows.  Doing everything localhost.  Ill try toxiproxy and see if I can reproduce.

Did you try higher latencies with toxiproxy?

With Clumsy the reason I selected 20ms is due to the following from clumsys FAQ

```
Lag is much more higher than the parameter set.
The gist is that the parameters are not intended to be an accurate measure. It's more of a parameter to control the behavior. Another thing is that the lag introduced is on per network packet. For example if clumsy introduced 20ms lag on both incoming and outgoing packets. A TCP connection needs at least 3 packets to establish. Then it's a 3*20ms in total. In the example of a web page, it might need to finish some HTTP requests in sequence before it starts rendering in the browser. Say it needs to complete requests 1, 2 and 3. When each is slowed down by 60ms the time it takes to start rendering would be delayed by 3*60=180ms. So don't worry too much when clumsy makes things slow too much :)
```

**Comment by lukebakken** [comment]
I also tried 1 second with no difference. Toxiproxy should only have been introducing latency to packets going from the C# receiver _to_ RabbitMQ, which would only be TCP ACKs. I don't even know if it operates at that layer, to be honest. Clumsy probably hooks into some dark corner of the Win32 socket API, which still doesn't explain the C# vs Python difference since both _should_ be using the same underlying API. At least now the source exists to verify that if you'd like to dig that deep.
